### ISSUE TITLE
Robotframework keyword access timeout is 10 seconds , this can be changed to higher number 

### ISSUE THREAD

**Issue by jagadeesanm-jag** [comick/node-robotremoteserver#4]
I am using the remotelibrary with nodejs server , robot framework throws error if keyword execution takes longer time than 10 seconds . Can this will be changed to some higher number  to wait for till longer time period . ? . This is completely blocking my activity .

**Comment by comick** [comment]
Server constructor takes options. One of these options is `timeout` configuring the number of msecs. Default is 10000. https://github.com/comick/node-robotremoteserver/blob/master/lib/robotremote.js#L10

**Comment by jagadeesanm-jag** [comment]
I got it . Thanks .


Warm Regards,
Jag
